# The version of the docker-compose.yml format
version: "3"

# The configuration of this container
services:
  jupyterlab:
    build: . # to use ./Dockerfile
    volumes:
      - $PWD:/tmp/work
    working_dir: /tmp/work
    ports:
      - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''